# Netlify build configuration
[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Static export
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
